In [3]:
import cv2 as cv
import numpy as np

img_bgr = cv.imread("Problem01_0300.bmp")

img_gray = cv.cvtColor(img_bgr, cv.COLOR_BGR2GRAY)

[[61 61 61 ... 60 61 60]
 [61 61 61 ... 61 61 61]
 [61 61 61 ... 61 60 60]
 ...
 [61 61 61 ... 61 61 61]
 [61 61 61 ... 61 61 61]
 [61 61 61 ... 61 61 61]]


In [6]:
np.set_printoptions(threshold=np.inf)
print(img_gray[300])
labele = np.zeros

[60 60 60 61 61 60 60 60 60 60 60 60 60 60 60 60 61 60 60 60 60 60 60 60
 61 61 60 60 60 60 60 60 60 60 60 60 60 60 60 61 61 61 61 61 60 61 61 61
 60 60 61 61 61 61 61 61 60 61 61 60 61 61 61 61 60 60 60 61 61 61 60 61
 61 61 61 61 61 61 63 64 64 64 65 65 65 65 65 65 65 65 65 65 65 65 65 65
 65 65 65 65 65 65 65 65 65 65 65 65 65 65 64 64 63 62 62 62 61 61 61 62
 62 62 62 62 62 62 62 62 61 61 61 62 62 61 61 62 62 62 62 62 62 62 62 62
 61 62 62 62 63 63 65 66 70 76 78 80 80 80 80 80 79 79 79 78 79 78 79 79
 78 78 78 78 78 78 77 78 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77
 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 76 77 77 77 77 76 76
 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76
 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76
 76 76 76 76 76 76 76 76 76 75 75 76 76 76 76 76 76 75 75 76 75 75 75 76
 76 76 76 76 76 76 75 75 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76
 75 76 76 76 76 76 76 76 76 76 75 75 76 76 76 76 76